
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro 

  mediccareapi:
    image: ${DOCKER_REGISTRY-}mediccareapi
    build:
      context: .
      dockerfile: ../MedicCare.Api/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=user;User Id=user;Password=password;

volumes:
  postgres_data: